//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CayGiaPha
{
    using System;
    using System.Collections.Generic;
    
    public partial class BirthPlace
    {
        public int BirthPlaceID { get; set; }
        public string BirthPlaceName { get; set; }
        public Nullable<int> TreeID { get; set; }
    }
}
