//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CayGiaPha
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CGPEntities : DbContext
    {
        public CGPEntities()
            : base("name=CGPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AchievementDetail> AchievementDetails { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<BirthPlace> BirthPlaces { get; set; }
        public virtual DbSet<BurialPlace> BurialPlaces { get; set; }
        public virtual DbSet<CauseOfDeath> CauseOfDeaths { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<ListAchievement> ListAchievements { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Relationship> Relationships { get; set; }
        public virtual DbSet<Tree> Trees { get; set; }
    }
}
